version: '3'

services:
  database:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - database_data:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - .:/var/www/html

volumes:
  database_data:
