controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login_render:
    path: /login
    controller: App\Controller\LoginController::renderLoginForm
    methods: ['GET']

app_login_request_process:
    path: /login
    controller: App\Controller\LoginController::processLoginRequest
    methods: ['POST']

app_userregister_render:
    path: /register
    controller: App\Controller\UserRegistrationController::renderUserRegistrationForm
    methods: ['GET']

app_register_request_process:
    path: /register
    controller: App\Controller\UserRegistrationController::processRegisterRequest
    methods: ['POST']

app_user_order_listing_render:
  path: /home
  controller: App\Controller\UserOrdersController::renderHome
  methods: ['GET']

app_user_logout:
    path: /logout
    controller: App\Controller\LoginController::processLogoutRequest
    methods: ['GET']

app_adm_dashboard_render:
  path: /dashboard
  controller: App\Controller\AdmDonationsDashboardController::renderDashboard
  methods: ['GET']

app_home_orders_rendering:
  path: /orders
  controller: App\Controller\UserOrdersController::renderOrders
  methods: ['GET']

app_user_order_edit:
  path: /order/edit/{id}
  controller: App\Controller\UserOrdersController::processFormEditOrderRequest
  methods: ['GET']

app_user_order_edit_save:
  path: /order/edit/{id}
  controller: App\Controller\UserOrdersController::processEditOrderRequest
  methods: ['PUT']

app_order_register_render:
  path: /order
  controller: App\Controller\UserOrdersController::registerOrderRender
  methods: ['GET']

app_process_order_register_request:
  path: /order
  controller: App\Controller\UserOrdersController::processRegisterOrderRequest
  methods: ['POST']


